### ISSUE TITLE
Modifiers sort

### ISSUE THREAD

**Issue by sd1ver** [nolequen/idea-inspections-plugin#5]
Current inspection profile places NotNull/Nullable modifiers before access modifier.
`@NotNull
  private Packet createPacket(...)`

But IDEA inspection profile requires other modifiers order:
`private @NotNull Packet createPacket(...)`

**Comment by nolequen** [comment]
I think it should be done with appropriate option in inspection settings.

**Comment by nolequen** [comment]
Fixed in v0.3.2
